body:
  - type: markdown
    attributes:
      value: >
        ⚠️ This category is solely for conversations related to Security Onion 2.4 ⚠️
  - type: dropdown
    attributes:
      label: Installation Method
      description: How did you install Security Onion?
      options:
        - Security Onion ISO image
        - Network installation on Red Hat derivative like Oracle, Rocky, Alma, etc.
        - Network installation on Ubuntu
        - Network installation on Debian
        - Other (please provide detail)
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Description
      description: >
        Is this discussion about installation, configuration, upgrading, or other?
      options:
        - installation
        - configuration
        - upgrading
        - other (please provide detail)
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Installation Type
      description: >
        When you installed, did you choose Import, Eval, Standalone, Distributed?
      options:
        - Import
        - Eval
        - Standalone
        - Distributed
        - other (please provide detail)
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Hardware specs
      description: >
        Does your hardware meet or exceed the minimum requirements for your installation type as shown at https://docs.securityonion.net/en/2.4/hardware.html?
      options:
        - Meets minimum requirements
        - Exceeds minimum requirements
        - Does not meet minimum requirements
        - other (please provide detail)
    validations:
      required: true
  - type: textarea
    attributes:
      label: Description
      description: When you installed, did you choose Import, Eval, Standalone, Distributed?
      placeholder: >-
        STOP! This category is only for discussions on GitHub Issues and
        GitHub Projects. GitHub Issues are the issues you open in a repo to
        track your work. NOT issues you are having with GitHub or a GitHub
        product. GitHub Projects are project boards you can create for example
        Kanban boards, to track your work. NOT projects on GitHub.


        We know the "issues" and ‘projects” naming conventions can be a little confusing.


        To report an issue with another area of the GitHub, use the correct product category, if one does not exist, use the General category. To ensure you receive a timely response and connect with the proper team(s) make sure you are posting  in the correct category.
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Guidelines
      options:
        - label: I have read the above statement and can confirm my post is relevant to
            the GitHub feature areas
            [Issues](https://docs.github.com/en/issues/tracking-your-work-with-issues/about-issues)
            and/or
            [Projects](https://docs.github.com/en/issues/planning-and-tracking-with-projects/learning-about-projects/about-projects).
          required: true
